# Development Dockerfile for Webpack with HMR
FROM node:22-alpine

ARG BACKEND_URL=http://localhost:3001/api/v1
WORKDIR /app

COPY ./package.json .

RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 8080 

CMD ["npm", "run", "dev"]