services:
  home-database:
    image: mongo
    ports:
      - "27017:27017"
  home-backend:
    build: server/
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://host.docker.internal:27017/home
    ports:
      - "3000:3000"
    depends_on:
      - home-database
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app/client
          ignore:
            - node_modules/
        - action: sync
          path: ./dist
          target: /app/dist
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  home-frontend:
    build:
      context: ./client
      args:
        VITE_BACKEND_URL: http://localhost:3000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - home-backend
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app/client
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
