services:
  home-database:
    image: mongo
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
  home-backend:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://home-database:27017/home
      - NODE_ENV=development
      - DRIME_URL=https://app.drime.cloud/api/v1
      - DRIME_TOKEN=drime_token
      - DRIME_EMAIL=drime_email
      - DRIME_PASS=drime_pass
      - DADATA_URL=http://mock-server:3004
      - DADATA_API_KEY=mock-key
      - NOMINATIM_URL=http://mock-server:3004
      - ACCESS_TOKEN_SECRET=access_token_secret
      - REFRESH_TOKEN_SECRET=refresh_token_secret
      - E2E_LOGIN=shevdi
      - E2E_PASSWORD=pass
      - RATE_LIMIT_LOGIN_MAX=50
    ports:
      - "3001:3001"
    depends_on:
      - home-database
  home-frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        BACKEND_URL: "http://localhost:3001/api/v1"
    environment:
      - BACKEND_URL=http://localhost:3001/api/v1
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Important for file watching in Docker
    ports:
      - "3000:3000"
    depends_on:
      - home-backend
