services:
  home-database:
    image: mongo
    ports:
      - "27017:27017"
  home-backend:
    build:
      context: ./server
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://host.docker.internal:27017/home
    ports:
      - "3001:3001"
    depends_on:
      - home-database
  home-frontend:
    build:
      context: ./client
      args:
        BACKEND_URL: http://localhost:3001/api/v1
    environment:
      BACKEND_URL: http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - home-backend
