export { WelcomePage } from './Welcome/Welcome'
export { ProjectsPage } from './Projects/Projects'
export { EditWelcomePage } from './Welcome/EditWelcome'
export { EditProjectsPage } from './Projects/EditProjects'
export { PhotoPage, PhotosPage, EditPhotoPage, UploadPhotoPage } from './Photos'
export { LoginPage } from './Login/Login'
export { NotFoundPage } from './NotFound/NotFound'
